version: '3.8'

services:
  backend:
    build: ./backend
    ports: 
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-networks
  
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-networks

volumes:
  - mongo-data

networks:
  - app-networks
  
